name: Deploy Shared Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/shared/*.tf

jobs:
  deploy:
    name: Deploy shared infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Google Cloud Credentials
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.TF_DEPLOYER_KEY }}'
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check
        working-directory: infrastructure/shared
      - run: terraform init
        working-directory: infrastructure/shared
      - run: terraform validate
        working-directory: infrastructure/shared
      - run: terraform apply -auto-approve
        working-directory: infrastructure/shared
